# Generated by Django 5.1.3 on 2025-02-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_alter_product_image_product_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagory',
            new_name='category',
        ),
    ]
